# netlify.toml — tells Netlify where your functions live
[build]
  publish = "."            # your static site root (where index.html lives)
  functions = "netlify/functions"

# Optional: force clean content-type for the API path
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
